version: '3'

services:
  bot:
    build:
      context: .
      dockerfile: ./Dockerfile
    container_name: bigsmoke
    env_file:
      - .env
    depends_on:
      - redis
      - mongo
    links:
      - redis
      - mongo

  redis:
    image: redis:5-alpine
    container_name: redis
    ports:
      - "6379:6379"

  mongo:
    image: mongo:latest
    container_name: mongo
    ports:
      - "27017:27017"
    volumes:
      - db-data:/data/db
      - mongo-config:/data/configdb

volumes:
  db-data:
  mongo-config:
